// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clientmanager

import (
	"context"

	"github.com/fishtre-compagnie/husonym/backend/gen/go/db"
	"github.com/fishtre-compagnie/husonym/backend/sql/postgresql/models"
	"github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDB is an autogenerated mock type for the DB type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// GetTemporalConfigByAccount provides a mock function for the type MockDB
func (_mock *MockDB) GetTemporalConfigByAccount(ctx context.Context, db db_queries.DBTX, accountId pgtype.UUID) (*pg_models.TemporalConfig, error) {
	ret := _mock.Called(ctx, db, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetTemporalConfigByAccount")
	}

	var r0 *pg_models.TemporalConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db_queries.DBTX, pgtype.UUID) (*pg_models.TemporalConfig, error)); ok {
		return returnFunc(ctx, db, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db_queries.DBTX, pgtype.UUID) *pg_models.TemporalConfig); ok {
		r0 = returnFunc(ctx, db, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pg_models.TemporalConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db_queries.DBTX, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, db, accountId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_GetTemporalConfigByAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemporalConfigByAccount'
type MockDB_GetTemporalConfigByAccount_Call struct {
	*mock.Call
}

// GetTemporalConfigByAccount is a helper method to define mock.On call
//   - ctx context.Context
//   - db db_queries.DBTX
//   - accountId pgtype.UUID
func (_e *MockDB_Expecter) GetTemporalConfigByAccount(ctx any, db any, accountId any) *MockDB_GetTemporalConfigByAccount_Call {
	return &MockDB_GetTemporalConfigByAccount_Call{Call: _e.mock.On("GetTemporalConfigByAccount", ctx, db, accountId)}
}

func (_c *MockDB_GetTemporalConfigByAccount_Call) Run(run func(ctx context.Context, db db_queries.DBTX, accountId pgtype.UUID)) *MockDB_GetTemporalConfigByAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(db_queries.DBTX)
		}
		var arg2 pgtype.UUID
		if args[2] != nil {
			arg2 = args[2].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDB_GetTemporalConfigByAccount_Call) Return(temporalConfig *pg_models.TemporalConfig, err error) *MockDB_GetTemporalConfigByAccount_Call {
	_c.Call.Return(temporalConfig, err)
	return _c
}

func (_c *MockDB_GetTemporalConfigByAccount_Call) RunAndReturn(run func(ctx context.Context, db db_queries.DBTX, accountId pgtype.UUID) (*pg_models.TemporalConfig, error)) *MockDB_GetTemporalConfigByAccount_Call {
	_c.Call.Return(run)
	return _c
}
