// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clientmanager

import (
	"context"
	"log/slog"

	mock "github.com/stretchr/testify/mock"
	"go.temporal.io/api/workflow/v1"
	"go.temporal.io/api/workflowservice/v1"
	"go.temporal.io/sdk/client"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// CancelWorkflow provides a mock function for the type MockInterface
func (_mock *MockInterface) CancelWorkflow(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, workflowId, logger)

	if len(ret) == 0 {
		panic("no return value specified for CancelWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_CancelWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelWorkflow'
type MockInterface_CancelWorkflow_Call struct {
	*mock.Call
}

// CancelWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - workflowId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) CancelWorkflow(ctx any, accountId any, workflowId any, logger any) *MockInterface_CancelWorkflow_Call {
	return &MockInterface_CancelWorkflow_Call{Call: _e.mock.On("CancelWorkflow", ctx, accountId, workflowId, logger)}
}

func (_c *MockInterface_CancelWorkflow_Call) Run(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger)) *MockInterface_CancelWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_CancelWorkflow_Call) Return(err error) *MockInterface_CancelWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_CancelWorkflow_Call) RunAndReturn(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) error) *MockInterface_CancelWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSchedule provides a mock function for the type MockInterface
func (_mock *MockInterface) CreateSchedule(ctx context.Context, accountId string, opts *client.ScheduleOptions, logger *slog.Logger) (string, error) {
	ret := _mock.Called(ctx, accountId, opts, logger)

	if len(ret) == 0 {
		panic("no return value specified for CreateSchedule")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *client.ScheduleOptions, *slog.Logger) (string, error)); ok {
		return returnFunc(ctx, accountId, opts, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *client.ScheduleOptions, *slog.Logger) string); ok {
		r0 = returnFunc(ctx, accountId, opts, logger)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *client.ScheduleOptions, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, opts, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_CreateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSchedule'
type MockInterface_CreateSchedule_Call struct {
	*mock.Call
}

// CreateSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - opts *client.ScheduleOptions
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) CreateSchedule(ctx any, accountId any, opts any, logger any) *MockInterface_CreateSchedule_Call {
	return &MockInterface_CreateSchedule_Call{Call: _e.mock.On("CreateSchedule", ctx, accountId, opts, logger)}
}

func (_c *MockInterface_CreateSchedule_Call) Run(run func(ctx context.Context, accountId string, opts *client.ScheduleOptions, logger *slog.Logger)) *MockInterface_CreateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *client.ScheduleOptions
		if args[2] != nil {
			arg2 = args[2].(*client.ScheduleOptions)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_CreateSchedule_Call) Return(s string, err error) *MockInterface_CreateSchedule_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockInterface_CreateSchedule_Call) RunAndReturn(run func(ctx context.Context, accountId string, opts *client.ScheduleOptions, logger *slog.Logger) (string, error)) *MockInterface_CreateSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSchedule provides a mock function for the type MockInterface
func (_mock *MockInterface) DeleteSchedule(ctx context.Context, accountId string, scheduleId string, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, scheduleId, logger)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSchedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, scheduleId, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_DeleteSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSchedule'
type MockInterface_DeleteSchedule_Call struct {
	*mock.Call
}

// DeleteSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - scheduleId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) DeleteSchedule(ctx any, accountId any, scheduleId any, logger any) *MockInterface_DeleteSchedule_Call {
	return &MockInterface_DeleteSchedule_Call{Call: _e.mock.On("DeleteSchedule", ctx, accountId, scheduleId, logger)}
}

func (_c *MockInterface_DeleteSchedule_Call) Run(run func(ctx context.Context, accountId string, scheduleId string, logger *slog.Logger)) *MockInterface_DeleteSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_DeleteSchedule_Call) Return(err error) *MockInterface_DeleteSchedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_DeleteSchedule_Call) RunAndReturn(run func(ctx context.Context, accountId string, scheduleId string, logger *slog.Logger) error) *MockInterface_DeleteSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkflowExecution provides a mock function for the type MockInterface
func (_mock *MockInterface) DeleteWorkflowExecution(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, workflowId, logger)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkflowExecution")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_DeleteWorkflowExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkflowExecution'
type MockInterface_DeleteWorkflowExecution_Call struct {
	*mock.Call
}

// DeleteWorkflowExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - workflowId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) DeleteWorkflowExecution(ctx any, accountId any, workflowId any, logger any) *MockInterface_DeleteWorkflowExecution_Call {
	return &MockInterface_DeleteWorkflowExecution_Call{Call: _e.mock.On("DeleteWorkflowExecution", ctx, accountId, workflowId, logger)}
}

func (_c *MockInterface_DeleteWorkflowExecution_Call) Run(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger)) *MockInterface_DeleteWorkflowExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_DeleteWorkflowExecution_Call) Return(err error) *MockInterface_DeleteWorkflowExecution_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_DeleteWorkflowExecution_Call) RunAndReturn(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) error) *MockInterface_DeleteWorkflowExecution_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeSchedule provides a mock function for the type MockInterface
func (_mock *MockInterface) DescribeSchedule(ctx context.Context, accountId string, scheduleId string, logger *slog.Logger) (*client.ScheduleDescription, error) {
	ret := _mock.Called(ctx, accountId, scheduleId, logger)

	if len(ret) == 0 {
		panic("no return value specified for DescribeSchedule")
	}

	var r0 *client.ScheduleDescription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) (*client.ScheduleDescription, error)); ok {
		return returnFunc(ctx, accountId, scheduleId, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) *client.ScheduleDescription); ok {
		r0 = returnFunc(ctx, accountId, scheduleId, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ScheduleDescription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, scheduleId, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_DescribeSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeSchedule'
type MockInterface_DescribeSchedule_Call struct {
	*mock.Call
}

// DescribeSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - scheduleId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) DescribeSchedule(ctx any, accountId any, scheduleId any, logger any) *MockInterface_DescribeSchedule_Call {
	return &MockInterface_DescribeSchedule_Call{Call: _e.mock.On("DescribeSchedule", ctx, accountId, scheduleId, logger)}
}

func (_c *MockInterface_DescribeSchedule_Call) Run(run func(ctx context.Context, accountId string, scheduleId string, logger *slog.Logger)) *MockInterface_DescribeSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_DescribeSchedule_Call) Return(scheduleDescription *client.ScheduleDescription, err error) *MockInterface_DescribeSchedule_Call {
	_c.Call.Return(scheduleDescription, err)
	return _c
}

func (_c *MockInterface_DescribeSchedule_Call) RunAndReturn(run func(ctx context.Context, accountId string, scheduleId string, logger *slog.Logger) (*client.ScheduleDescription, error)) *MockInterface_DescribeSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeSchedules provides a mock function for the type MockInterface
func (_mock *MockInterface) DescribeSchedules(ctx context.Context, accountId string, scheduleIds []string, logger *slog.Logger) ([]*DescribeSchedulesResponse, error) {
	ret := _mock.Called(ctx, accountId, scheduleIds, logger)

	if len(ret) == 0 {
		panic("no return value specified for DescribeSchedules")
	}

	var r0 []*DescribeSchedulesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, *slog.Logger) ([]*DescribeSchedulesResponse, error)); ok {
		return returnFunc(ctx, accountId, scheduleIds, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, *slog.Logger) []*DescribeSchedulesResponse); ok {
		r0 = returnFunc(ctx, accountId, scheduleIds, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*DescribeSchedulesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, scheduleIds, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_DescribeSchedules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeSchedules'
type MockInterface_DescribeSchedules_Call struct {
	*mock.Call
}

// DescribeSchedules is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - scheduleIds []string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) DescribeSchedules(ctx any, accountId any, scheduleIds any, logger any) *MockInterface_DescribeSchedules_Call {
	return &MockInterface_DescribeSchedules_Call{Call: _e.mock.On("DescribeSchedules", ctx, accountId, scheduleIds, logger)}
}

func (_c *MockInterface_DescribeSchedules_Call) Run(run func(ctx context.Context, accountId string, scheduleIds []string, logger *slog.Logger)) *MockInterface_DescribeSchedules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_DescribeSchedules_Call) Return(describeSchedulesResponses []*DescribeSchedulesResponse, err error) *MockInterface_DescribeSchedules_Call {
	_c.Call.Return(describeSchedulesResponses, err)
	return _c
}

func (_c *MockInterface_DescribeSchedules_Call) RunAndReturn(run func(ctx context.Context, accountId string, scheduleIds []string, logger *slog.Logger) ([]*DescribeSchedulesResponse, error)) *MockInterface_DescribeSchedules_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeWorklowExecution provides a mock function for the type MockInterface
func (_mock *MockInterface) DescribeWorklowExecution(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) (*workflowservice.DescribeWorkflowExecutionResponse, error) {
	ret := _mock.Called(ctx, accountId, workflowId, logger)

	if len(ret) == 0 {
		panic("no return value specified for DescribeWorklowExecution")
	}

	var r0 *workflowservice.DescribeWorkflowExecutionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) (*workflowservice.DescribeWorkflowExecutionResponse, error)); ok {
		return returnFunc(ctx, accountId, workflowId, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) *workflowservice.DescribeWorkflowExecutionResponse); ok {
		r0 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflowservice.DescribeWorkflowExecutionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_DescribeWorklowExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeWorklowExecution'
type MockInterface_DescribeWorklowExecution_Call struct {
	*mock.Call
}

// DescribeWorklowExecution is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - workflowId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) DescribeWorklowExecution(ctx any, accountId any, workflowId any, logger any) *MockInterface_DescribeWorklowExecution_Call {
	return &MockInterface_DescribeWorklowExecution_Call{Call: _e.mock.On("DescribeWorklowExecution", ctx, accountId, workflowId, logger)}
}

func (_c *MockInterface_DescribeWorklowExecution_Call) Run(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger)) *MockInterface_DescribeWorklowExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_DescribeWorklowExecution_Call) Return(describeWorkflowExecutionResponse *workflowservice.DescribeWorkflowExecutionResponse, err error) *MockInterface_DescribeWorklowExecution_Call {
	_c.Call.Return(describeWorkflowExecutionResponse, err)
	return _c
}

func (_c *MockInterface_DescribeWorklowExecution_Call) RunAndReturn(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) (*workflowservice.DescribeWorkflowExecutionResponse, error)) *MockInterface_DescribeWorklowExecution_Call {
	_c.Call.Return(run)
	return _c
}

// DoesAccountHaveNamespace provides a mock function for the type MockInterface
func (_mock *MockInterface) DoesAccountHaveNamespace(ctx context.Context, accountId string, logger *slog.Logger) (bool, error) {
	ret := _mock.Called(ctx, accountId, logger)

	if len(ret) == 0 {
		panic("no return value specified for DoesAccountHaveNamespace")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *slog.Logger) (bool, error)); ok {
		return returnFunc(ctx, accountId, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *slog.Logger) bool); ok {
		r0 = returnFunc(ctx, accountId, logger)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_DoesAccountHaveNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoesAccountHaveNamespace'
type MockInterface_DoesAccountHaveNamespace_Call struct {
	*mock.Call
}

// DoesAccountHaveNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) DoesAccountHaveNamespace(ctx any, accountId any, logger any) *MockInterface_DoesAccountHaveNamespace_Call {
	return &MockInterface_DoesAccountHaveNamespace_Call{Call: _e.mock.On("DoesAccountHaveNamespace", ctx, accountId, logger)}
}

func (_c *MockInterface_DoesAccountHaveNamespace_Call) Run(run func(ctx context.Context, accountId string, logger *slog.Logger)) *MockInterface_DoesAccountHaveNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *slog.Logger
		if args[2] != nil {
			arg2 = args[2].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_DoesAccountHaveNamespace_Call) Return(b bool, err error) *MockInterface_DoesAccountHaveNamespace_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockInterface_DoesAccountHaveNamespace_Call) RunAndReturn(run func(ctx context.Context, accountId string, logger *slog.Logger) (bool, error)) *MockInterface_DoesAccountHaveNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetSyncJobTaskQueue provides a mock function for the type MockInterface
func (_mock *MockInterface) GetSyncJobTaskQueue(ctx context.Context, accountId string, logger *slog.Logger) (string, error) {
	ret := _mock.Called(ctx, accountId, logger)

	if len(ret) == 0 {
		panic("no return value specified for GetSyncJobTaskQueue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *slog.Logger) (string, error)); ok {
		return returnFunc(ctx, accountId, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *slog.Logger) string); ok {
		r0 = returnFunc(ctx, accountId, logger)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetSyncJobTaskQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSyncJobTaskQueue'
type MockInterface_GetSyncJobTaskQueue_Call struct {
	*mock.Call
}

// GetSyncJobTaskQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) GetSyncJobTaskQueue(ctx any, accountId any, logger any) *MockInterface_GetSyncJobTaskQueue_Call {
	return &MockInterface_GetSyncJobTaskQueue_Call{Call: _e.mock.On("GetSyncJobTaskQueue", ctx, accountId, logger)}
}

func (_c *MockInterface_GetSyncJobTaskQueue_Call) Run(run func(ctx context.Context, accountId string, logger *slog.Logger)) *MockInterface_GetSyncJobTaskQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *slog.Logger
		if args[2] != nil {
			arg2 = args[2].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInterface_GetSyncJobTaskQueue_Call) Return(s string, err error) *MockInterface_GetSyncJobTaskQueue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockInterface_GetSyncJobTaskQueue_Call) RunAndReturn(run func(ctx context.Context, accountId string, logger *slog.Logger) (string, error)) *MockInterface_GetSyncJobTaskQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowExecutionById provides a mock function for the type MockInterface
func (_mock *MockInterface) GetWorkflowExecutionById(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) (*workflow.WorkflowExecutionInfo, error) {
	ret := _mock.Called(ctx, accountId, workflowId, logger)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowExecutionById")
	}

	var r0 *workflow.WorkflowExecutionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) (*workflow.WorkflowExecutionInfo, error)); ok {
		return returnFunc(ctx, accountId, workflowId, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) *workflow.WorkflowExecutionInfo); ok {
		r0 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*workflow.WorkflowExecutionInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetWorkflowExecutionById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowExecutionById'
type MockInterface_GetWorkflowExecutionById_Call struct {
	*mock.Call
}

// GetWorkflowExecutionById is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - workflowId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) GetWorkflowExecutionById(ctx any, accountId any, workflowId any, logger any) *MockInterface_GetWorkflowExecutionById_Call {
	return &MockInterface_GetWorkflowExecutionById_Call{Call: _e.mock.On("GetWorkflowExecutionById", ctx, accountId, workflowId, logger)}
}

func (_c *MockInterface_GetWorkflowExecutionById_Call) Run(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger)) *MockInterface_GetWorkflowExecutionById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_GetWorkflowExecutionById_Call) Return(workflowExecutionInfo *workflow.WorkflowExecutionInfo, err error) *MockInterface_GetWorkflowExecutionById_Call {
	_c.Call.Return(workflowExecutionInfo, err)
	return _c
}

func (_c *MockInterface_GetWorkflowExecutionById_Call) RunAndReturn(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) (*workflow.WorkflowExecutionInfo, error)) *MockInterface_GetWorkflowExecutionById_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowExecutionsByScheduleIds provides a mock function for the type MockInterface
func (_mock *MockInterface) GetWorkflowExecutionsByScheduleIds(ctx context.Context, accountId string, scheduleIds []string, logger *slog.Logger) ([]*workflow.WorkflowExecutionInfo, error) {
	ret := _mock.Called(ctx, accountId, scheduleIds, logger)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowExecutionsByScheduleIds")
	}

	var r0 []*workflow.WorkflowExecutionInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, *slog.Logger) ([]*workflow.WorkflowExecutionInfo, error)); ok {
		return returnFunc(ctx, accountId, scheduleIds, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, *slog.Logger) []*workflow.WorkflowExecutionInfo); ok {
		r0 = returnFunc(ctx, accountId, scheduleIds, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*workflow.WorkflowExecutionInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, scheduleIds, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetWorkflowExecutionsByScheduleIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowExecutionsByScheduleIds'
type MockInterface_GetWorkflowExecutionsByScheduleIds_Call struct {
	*mock.Call
}

// GetWorkflowExecutionsByScheduleIds is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - scheduleIds []string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) GetWorkflowExecutionsByScheduleIds(ctx any, accountId any, scheduleIds any, logger any) *MockInterface_GetWorkflowExecutionsByScheduleIds_Call {
	return &MockInterface_GetWorkflowExecutionsByScheduleIds_Call{Call: _e.mock.On("GetWorkflowExecutionsByScheduleIds", ctx, accountId, scheduleIds, logger)}
}

func (_c *MockInterface_GetWorkflowExecutionsByScheduleIds_Call) Run(run func(ctx context.Context, accountId string, scheduleIds []string, logger *slog.Logger)) *MockInterface_GetWorkflowExecutionsByScheduleIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_GetWorkflowExecutionsByScheduleIds_Call) Return(workflowExecutionInfos []*workflow.WorkflowExecutionInfo, err error) *MockInterface_GetWorkflowExecutionsByScheduleIds_Call {
	_c.Call.Return(workflowExecutionInfos, err)
	return _c
}

func (_c *MockInterface_GetWorkflowExecutionsByScheduleIds_Call) RunAndReturn(run func(ctx context.Context, accountId string, scheduleIds []string, logger *slog.Logger) ([]*workflow.WorkflowExecutionInfo, error)) *MockInterface_GetWorkflowExecutionsByScheduleIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowHistory provides a mock function for the type MockInterface
func (_mock *MockInterface) GetWorkflowHistory(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) (client.HistoryEventIterator, error) {
	ret := _mock.Called(ctx, accountId, workflowId, logger)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowHistory")
	}

	var r0 client.HistoryEventIterator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) (client.HistoryEventIterator, error)); ok {
		return returnFunc(ctx, accountId, workflowId, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) client.HistoryEventIterator); ok {
		r0 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.HistoryEventIterator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetWorkflowHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowHistory'
type MockInterface_GetWorkflowHistory_Call struct {
	*mock.Call
}

// GetWorkflowHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - workflowId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) GetWorkflowHistory(ctx any, accountId any, workflowId any, logger any) *MockInterface_GetWorkflowHistory_Call {
	return &MockInterface_GetWorkflowHistory_Call{Call: _e.mock.On("GetWorkflowHistory", ctx, accountId, workflowId, logger)}
}

func (_c *MockInterface_GetWorkflowHistory_Call) Run(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger)) *MockInterface_GetWorkflowHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_GetWorkflowHistory_Call) Return(historyEventIterator client.HistoryEventIterator, err error) *MockInterface_GetWorkflowHistory_Call {
	_c.Call.Return(historyEventIterator, err)
	return _c
}

func (_c *MockInterface_GetWorkflowHistory_Call) RunAndReturn(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) (client.HistoryEventIterator, error)) *MockInterface_GetWorkflowHistory_Call {
	_c.Call.Return(run)
	return _c
}

// PauseSchedule provides a mock function for the type MockInterface
func (_mock *MockInterface) PauseSchedule(ctx context.Context, accountId string, scheduleId string, opts *client.SchedulePauseOptions, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, scheduleId, opts, logger)

	if len(ret) == 0 {
		panic("no return value specified for PauseSchedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *client.SchedulePauseOptions, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, scheduleId, opts, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_PauseSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseSchedule'
type MockInterface_PauseSchedule_Call struct {
	*mock.Call
}

// PauseSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - scheduleId string
//   - opts *client.SchedulePauseOptions
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) PauseSchedule(ctx any, accountId any, scheduleId any, opts any, logger any) *MockInterface_PauseSchedule_Call {
	return &MockInterface_PauseSchedule_Call{Call: _e.mock.On("PauseSchedule", ctx, accountId, scheduleId, opts, logger)}
}

func (_c *MockInterface_PauseSchedule_Call) Run(run func(ctx context.Context, accountId string, scheduleId string, opts *client.SchedulePauseOptions, logger *slog.Logger)) *MockInterface_PauseSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *client.SchedulePauseOptions
		if args[3] != nil {
			arg3 = args[3].(*client.SchedulePauseOptions)
		}
		var arg4 *slog.Logger
		if args[4] != nil {
			arg4 = args[4].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInterface_PauseSchedule_Call) Return(err error) *MockInterface_PauseSchedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_PauseSchedule_Call) RunAndReturn(run func(ctx context.Context, accountId string, scheduleId string, opts *client.SchedulePauseOptions, logger *slog.Logger) error) *MockInterface_PauseSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// RunWorkflow provides a mock function for the type MockInterface
func (_mock *MockInterface) RunWorkflow(ctx context.Context, accountId string, opts *client.StartWorkflowOptions, workflow1 any, arg any, valuePtr any, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, opts, workflow1, arg, valuePtr, logger)

	if len(ret) == 0 {
		panic("no return value specified for RunWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *client.StartWorkflowOptions, any, any, any, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, opts, workflow1, arg, valuePtr, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_RunWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunWorkflow'
type MockInterface_RunWorkflow_Call struct {
	*mock.Call
}

// RunWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - opts *client.StartWorkflowOptions
//   - workflow1 any
//   - arg any
//   - valuePtr any
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) RunWorkflow(ctx any, accountId any, opts any, workflow1 any, arg any, valuePtr any, logger any) *MockInterface_RunWorkflow_Call {
	return &MockInterface_RunWorkflow_Call{Call: _e.mock.On("RunWorkflow", ctx, accountId, opts, workflow1, arg, valuePtr, logger)}
}

func (_c *MockInterface_RunWorkflow_Call) Run(run func(ctx context.Context, accountId string, opts *client.StartWorkflowOptions, workflow1 any, arg any, valuePtr any, logger *slog.Logger)) *MockInterface_RunWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *client.StartWorkflowOptions
		if args[2] != nil {
			arg2 = args[2].(*client.StartWorkflowOptions)
		}
		var arg3 any
		if args[3] != nil {
			arg3 = args[3].(any)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		var arg5 any
		if args[5] != nil {
			arg5 = args[5].(any)
		}
		var arg6 *slog.Logger
		if args[6] != nil {
			arg6 = args[6].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockInterface_RunWorkflow_Call) Return(err error) *MockInterface_RunWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_RunWorkflow_Call) RunAndReturn(run func(ctx context.Context, accountId string, opts *client.StartWorkflowOptions, workflow1 any, arg any, valuePtr any, logger *slog.Logger) error) *MockInterface_RunWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// TerminateWorkflow provides a mock function for the type MockInterface
func (_mock *MockInterface) TerminateWorkflow(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, workflowId, logger)

	if len(ret) == 0 {
		panic("no return value specified for TerminateWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, workflowId, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_TerminateWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TerminateWorkflow'
type MockInterface_TerminateWorkflow_Call struct {
	*mock.Call
}

// TerminateWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - workflowId string
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) TerminateWorkflow(ctx any, accountId any, workflowId any, logger any) *MockInterface_TerminateWorkflow_Call {
	return &MockInterface_TerminateWorkflow_Call{Call: _e.mock.On("TerminateWorkflow", ctx, accountId, workflowId, logger)}
}

func (_c *MockInterface_TerminateWorkflow_Call) Run(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger)) *MockInterface_TerminateWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *slog.Logger
		if args[3] != nil {
			arg3 = args[3].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInterface_TerminateWorkflow_Call) Return(err error) *MockInterface_TerminateWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_TerminateWorkflow_Call) RunAndReturn(run func(ctx context.Context, accountId string, workflowId string, logger *slog.Logger) error) *MockInterface_TerminateWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerSchedule provides a mock function for the type MockInterface
func (_mock *MockInterface) TriggerSchedule(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleTriggerOptions, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, scheduleId, opts, logger)

	if len(ret) == 0 {
		panic("no return value specified for TriggerSchedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *client.ScheduleTriggerOptions, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, scheduleId, opts, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_TriggerSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerSchedule'
type MockInterface_TriggerSchedule_Call struct {
	*mock.Call
}

// TriggerSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - scheduleId string
//   - opts *client.ScheduleTriggerOptions
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) TriggerSchedule(ctx any, accountId any, scheduleId any, opts any, logger any) *MockInterface_TriggerSchedule_Call {
	return &MockInterface_TriggerSchedule_Call{Call: _e.mock.On("TriggerSchedule", ctx, accountId, scheduleId, opts, logger)}
}

func (_c *MockInterface_TriggerSchedule_Call) Run(run func(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleTriggerOptions, logger *slog.Logger)) *MockInterface_TriggerSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *client.ScheduleTriggerOptions
		if args[3] != nil {
			arg3 = args[3].(*client.ScheduleTriggerOptions)
		}
		var arg4 *slog.Logger
		if args[4] != nil {
			arg4 = args[4].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInterface_TriggerSchedule_Call) Return(err error) *MockInterface_TriggerSchedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_TriggerSchedule_Call) RunAndReturn(run func(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleTriggerOptions, logger *slog.Logger) error) *MockInterface_TriggerSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// UnpauseSchedule provides a mock function for the type MockInterface
func (_mock *MockInterface) UnpauseSchedule(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleUnpauseOptions, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, scheduleId, opts, logger)

	if len(ret) == 0 {
		panic("no return value specified for UnpauseSchedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *client.ScheduleUnpauseOptions, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, scheduleId, opts, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_UnpauseSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpauseSchedule'
type MockInterface_UnpauseSchedule_Call struct {
	*mock.Call
}

// UnpauseSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - scheduleId string
//   - opts *client.ScheduleUnpauseOptions
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) UnpauseSchedule(ctx any, accountId any, scheduleId any, opts any, logger any) *MockInterface_UnpauseSchedule_Call {
	return &MockInterface_UnpauseSchedule_Call{Call: _e.mock.On("UnpauseSchedule", ctx, accountId, scheduleId, opts, logger)}
}

func (_c *MockInterface_UnpauseSchedule_Call) Run(run func(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleUnpauseOptions, logger *slog.Logger)) *MockInterface_UnpauseSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *client.ScheduleUnpauseOptions
		if args[3] != nil {
			arg3 = args[3].(*client.ScheduleUnpauseOptions)
		}
		var arg4 *slog.Logger
		if args[4] != nil {
			arg4 = args[4].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInterface_UnpauseSchedule_Call) Return(err error) *MockInterface_UnpauseSchedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_UnpauseSchedule_Call) RunAndReturn(run func(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleUnpauseOptions, logger *slog.Logger) error) *MockInterface_UnpauseSchedule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSchedule provides a mock function for the type MockInterface
func (_mock *MockInterface) UpdateSchedule(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleUpdateOptions, logger *slog.Logger) error {
	ret := _mock.Called(ctx, accountId, scheduleId, opts, logger)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSchedule")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *client.ScheduleUpdateOptions, *slog.Logger) error); ok {
		r0 = returnFunc(ctx, accountId, scheduleId, opts, logger)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInterface_UpdateSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSchedule'
type MockInterface_UpdateSchedule_Call struct {
	*mock.Call
}

// UpdateSchedule is a helper method to define mock.On call
//   - ctx context.Context
//   - accountId string
//   - scheduleId string
//   - opts *client.ScheduleUpdateOptions
//   - logger *slog.Logger
func (_e *MockInterface_Expecter) UpdateSchedule(ctx any, accountId any, scheduleId any, opts any, logger any) *MockInterface_UpdateSchedule_Call {
	return &MockInterface_UpdateSchedule_Call{Call: _e.mock.On("UpdateSchedule", ctx, accountId, scheduleId, opts, logger)}
}

func (_c *MockInterface_UpdateSchedule_Call) Run(run func(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleUpdateOptions, logger *slog.Logger)) *MockInterface_UpdateSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *client.ScheduleUpdateOptions
		if args[3] != nil {
			arg3 = args[3].(*client.ScheduleUpdateOptions)
		}
		var arg4 *slog.Logger
		if args[4] != nil {
			arg4 = args[4].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockInterface_UpdateSchedule_Call) Return(err error) *MockInterface_UpdateSchedule_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInterface_UpdateSchedule_Call) RunAndReturn(run func(ctx context.Context, accountId string, scheduleId string, opts *client.ScheduleUpdateOptions, logger *slog.Logger) error) *MockInterface_UpdateSchedule_Call {
	_c.Call.Return(run)
	return _c
}
