// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package husonym_gcp

import (
	"context"
	"log/slog"

	"github.com/fishtre-compagnie/husonym/backend/gen/go/protos/mgmt/v1alpha1"
	mock "github.com/stretchr/testify/mock"
)

// NewMockManagerInterface creates a new instance of MockManagerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManagerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManagerInterface {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockManagerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockManagerInterface is an autogenerated mock type for the ManagerInterface type
type MockManagerInterface struct {
	mock.Mock
}

type MockManagerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManagerInterface) EXPECT() *MockManagerInterface_Expecter {
	return &MockManagerInterface_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function for the type MockManagerInterface
func (_mock *MockManagerInterface) GetClient(ctx context.Context, config *mgmtv1alpha1.GcpCloudStorageConnectionConfig, logger *slog.Logger) (ClientInterface, error) {
	ret := _mock.Called(ctx, config, logger)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 ClientInterface
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *mgmtv1alpha1.GcpCloudStorageConnectionConfig, *slog.Logger) (ClientInterface, error)); ok {
		return returnFunc(ctx, config, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *mgmtv1alpha1.GcpCloudStorageConnectionConfig, *slog.Logger) ClientInterface); ok {
		r0 = returnFunc(ctx, config, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ClientInterface)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *mgmtv1alpha1.GcpCloudStorageConnectionConfig, *slog.Logger) error); ok {
		r1 = returnFunc(ctx, config, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerInterface_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockManagerInterface_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - config *mgmtv1alpha1.GcpCloudStorageConnectionConfig
//   - logger *slog.Logger
func (_e *MockManagerInterface_Expecter) GetClient(ctx any, config any, logger any) *MockManagerInterface_GetClient_Call {
	return &MockManagerInterface_GetClient_Call{Call: _e.mock.On("GetClient", ctx, config, logger)}
}

func (_c *MockManagerInterface_GetClient_Call) Run(run func(ctx context.Context, config *mgmtv1alpha1.GcpCloudStorageConnectionConfig, logger *slog.Logger)) *MockManagerInterface_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *mgmtv1alpha1.GcpCloudStorageConnectionConfig
		if args[1] != nil {
			arg1 = args[1].(*mgmtv1alpha1.GcpCloudStorageConnectionConfig)
		}
		var arg2 *slog.Logger
		if args[2] != nil {
			arg2 = args[2].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockManagerInterface_GetClient_Call) Return(clientInterface ClientInterface, err error) *MockManagerInterface_GetClient_Call {
	_c.Call.Return(clientInterface, err)
	return _c
}

func (_c *MockManagerInterface_GetClient_Call) RunAndReturn(run func(ctx context.Context, config *mgmtv1alpha1.GcpCloudStorageConnectionConfig, logger *slog.Logger) (ClientInterface, error)) *MockManagerInterface_GetClient_Call {
	_c.Call.Return(run)
	return _c
}
