load('ext://restart_process', 'docker_build_with_restart')
load('ext://configmap', 'configmap_from_dict')
load('ext://namespace', 'namespace_create')

helpers = load_dynamic("../tilt/extensions/Tiltfile")
helmfile_with_local_chart = helpers['helmfile_with_local_chart']
helmfile = helpers['helmfile']

allow_k8s_contexts('kind-husonym-dev')

base_dir = os.path.dirname(__file__)

# when debugging can be handy to disable scrub
secret_settings(disable_scrub=True)

namespace_create('husonym', allow_duplicates=True)

local_resource(
  'husonym-api-gen',
  'scripts/gen.sh',
  deps=[
    'protos',
    'buf.gen.yaml',
    'buf.work.yaml',
    'buf-es.gen.yaml',
    'sql/postgresql/models',
    'sql/postgresql/queries',
  ],
  labels=['build']
)

# Watches and rebuilds Go code
local_resource(
  'husonym-api-build',
  'scripts/build.sh',
  deps=['.'],
  ignore=[
    '.git',
    'bin',
    '.gitignore',
    'protos',
    '.vscode',
    'README.md',
    '.github',
    'charts',
    'Makefile',
    'Dockerfile',
    'buf.gen.yaml',
    'buf.work.yaml',
    'buf-es.gen.yaml',
    'sql/postgresql/schema',
  ],
  labels=['build']
)

k8s_yaml(kustomize('./dev/yaml'))
k8s_yaml(helmfile('./dev/helm/db', helmfileDir=base_dir+'/dev/helm/db'))
k8s_resource('husonym-postgresql', labels=['db'], port_forwards=5432)

#   k8s_yaml(configmap_from_dict("dev-config", namespace=namespace, inputs = {
#       'AWS_ACCESS_KEY_ID'         : os.getenv('AWS_ACCESS_KEY_ID'),
#       'AWS_SECRET_ACCESS_KEY'     : os.getenv('AWS_SECRET_ACCESS_KEY'),
#       'AWS_SESSION_TOKEN'         : os.getenv('AWS_SESSION_TOKEN'),
#       'AWS_SECURITY_TOKEN'        : os.getenv('AWS_SECURITY_TOKEN'),
#       'AWS_REGION'                : os.getenv('AWS_REGION'),
# }))

k8s_yaml(helmfile_with_local_chart('husonym-api', base_dir + '/charts/api', helmfileDir=base_dir + '/dev/helm/api'))
# References the deployment
k8s_resource(
  'husonym-api',
  resource_deps=['husonym-postgresql'],
  labels=['backend'],
  port_forwards="8080:8080",
)
docker_build_with_restart(
  ref='husonym-api',
  context='.',
  entrypoint=['/app/mgmt'],
  dockerfile='./dev/build/Dockerfile.dev',
  only=['.env.dev', 'bin', 'sql'],
  live_update=[
    sync('bin', '/app'),
    sync('sql/postgresql/schema', '/app/migrations'),
    sync('.env.dev', '/app'),
  ],
)
