package job

import (
	"testing"

	mgmtv1alpha1 "github.com/fishtre-compagnie/husonym/backend/gen/go/protos/mgmt/v1alpha1"
	sqlmanager_shared "github.com/fishtre-compagnie/husonym/backend/pkg/sqlmanager/shared"
	"github.com/fishtre-compagnie/husonym/internal/transformers/catalog"
	"github.com/stretchr/testify/require"
)

func fits(t *testing.T, source mgmtv1alpha1.TransformerSource, column columnTraits) bool {
	t.Helper()
	transformer, ok := catalog.BySource(true)[source]
	require.True(t, ok, "%s is not in the catalogue", source)
	return transformerFits(transformer, column, mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_SYNC)
}

// Each branch of the UI's rule (shouldIncludeSystem), in its order.
func Test_TransformerFits(t *testing.T) {
	text := columnTraits{dataType: mgmtv1alpha1.TransformerDataType_TRANSFORMER_DATA_TYPE_STRING}
	integer := columnTraits{dataType: mgmtv1alpha1.TransformerDataType_TRANSFORMER_DATA_TYPE_INT64}

	t.Run("a generated column takes its default only", func(t *testing.T) {
		generated := text
		generated.generated, generated.hasDefault = true, true
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_DEFAULT, generated))
		require.False(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_PASSTHROUGH, generated))
	})

	t.Run("an identity takes its default, its value, or the scrambled one", func(t *testing.T) {
		for _, identity := range []string{"auto_increment", "IDENTITY(1,1)"} {
			column := integer
			column.identity = identity
			require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_TRANSFORM_SCRAMBLE_IDENTITY, column))
			require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_PASSTHROUGH, column))
			require.False(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_INT64, column))
		}
	})

	t.Run("an identity generated always takes its default or its value", func(t *testing.T) {
		column := integer
		column.identity = "a"
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_DEFAULT, column))
		require.False(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_TRANSFORM_SCRAMBLE_IDENTITY, column))
	})

	t.Run("an identity generated by default is an ordinary column", func(t *testing.T) {
		column := integer
		column.identity, column.hasDefault = "d", true
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_INT64, column))
	})

	t.Run("the default only where there is one", func(t *testing.T) {
		require.False(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_DEFAULT, text))
		withDefault := text
		withDefault.hasDefault = true
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_DEFAULT, withDefault))
	})

	t.Run("a foreign key keeps its value, or is computed by code", func(t *testing.T) {
		fk := integer
		fk.foreignKey = true
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_PASSTHROUGH, fk))
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_TRANSFORM_JAVASCRIPT, fk))
		require.False(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_INT64, fk))
		require.False(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_NULL, fk))
		fk.nullable = true
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_NULL, fk))
	})

	t.Run("the type of the column", func(t *testing.T) {
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_EMAIL, text))
		require.False(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_EMAIL, integer))
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_PASSTHROUGH, integer))
	})

	t.Run("null only on a nullable column", func(t *testing.T) {
		require.False(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_NULL, text))
		nullable := text
		nullable.nullable = true
		require.True(t, fits(t, mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_NULL, nullable))
	})

	t.Run("a transformer of another type of job", func(t *testing.T) {
		generateOnly := &mgmtv1alpha1.SystemTransformer{
			Source:            mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_EMAIL,
			DataTypes:         []mgmtv1alpha1.TransformerDataType{mgmtv1alpha1.TransformerDataType_TRANSFORMER_DATA_TYPE_STRING},
			SupportedJobTypes: []mgmtv1alpha1.SupportedJobType{mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_GENERATE},
		}
		require.False(t, transformerFits(generateOnly, text, mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_SYNC))
		require.True(t, transformerFits(generateOnly, text, mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_GENERATE))
	})
}

func Test_ValidateTransformers(t *testing.T) {
	config := func(source mgmtv1alpha1.TransformerSource) *mgmtv1alpha1.JobMappingTransformer {
		c, ok := catalog.DefaultConfig(source, true)
		require.True(t, ok)
		return &mgmtv1alpha1.JobMappingTransformer{Config: c}
	}
	stored := "s"
	columns := map[string]map[string]*sqlmanager_shared.DatabaseSchemaRow{
		"public.users": {
			"id":              {DataType: "uuid"},
			"email":           {DataType: "text"},
			"email_normalise": {DataType: "text", GeneratedType: &stored, ColumnDefault: "lower(email)"},
		},
		"public.orders": {
			"user_id": {DataType: "uuid"},
		},
	}
	foreignKeys := map[string][]*sqlmanager_shared.ForeignConstraint{
		"public.orders": {{
			Columns: []string{"user_id"}, NotNullable: []bool{true},
			ForeignKey: &sqlmanager_shared.ForeignKey{Table: "public.users", Columns: []string{"id"}},
		}},
	}
	mappings := []*mgmtv1alpha1.JobMapping{
		{Schema: "public", Table: "users", Column: "id", Transformer: config(mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_PASSTHROUGH)},
		{Schema: "public", Table: "users", Column: "email", Transformer: config(mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_EMAIL)},
		{Schema: "public", Table: "users", Column: "email_normalise", Transformer: config(mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_PASSTHROUGH)},
		{Schema: "public", Table: "orders", Column: "user_id", Transformer: config(mgmtv1alpha1.TransformerSource_TRANSFORMER_SOURCE_GENERATE_UUID)},
	}

	t.Run("reports each transformer that does not fit, with those that do", func(t *testing.T) {
		jmv := NewJobMappingsValidator(mappings, WithJobType(mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_SYNC))
		jmv.ValidateTransformers(columns, foreignKeys, nil)

		errors := jmv.GetColumnErrors()
		require.Equal(t, []*mgmtv1alpha1.ColumnError_ColumnErrorReport{{
			Code:    mgmtv1alpha1.ColumnError_COLUMN_ERROR_CODE_TRANSFORMER_NOT_ALLOWED,
			Message: "passthrough does not fit this column; it takes generate_default",
		}}, errors["public.users"]["email_normalise"])
		require.Equal(t, []*mgmtv1alpha1.ColumnError_ColumnErrorReport{{
			Code:    mgmtv1alpha1.ColumnError_COLUMN_ERROR_CODE_TRANSFORMER_NOT_ALLOWED,
			Message: "generate_uuid does not fit this column; it takes passthrough, transform_javascript",
		}}, errors["public.orders"]["user_id"])
		require.Empty(t, errors["public.users"]["email"])
		require.Empty(t, errors["public.users"]["id"])
	})

	t.Run("a virtual foreign key holds its column as a real one does", func(t *testing.T) {
		jmv := NewJobMappingsValidator(mappings, WithJobType(mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_SYNC))
		jmv.ValidateTransformers(columns, nil, []*mgmtv1alpha1.VirtualForeignConstraint{{
			Schema: "public", Table: "orders", Columns: []string{"user_id"},
			ForeignKey: &mgmtv1alpha1.VirtualForeignKey{Schema: "public", Table: "users", Columns: []string{"id"}},
		}})
		require.NotEmpty(t, jmv.GetColumnErrors()["public.orders"]["user_id"])
	})

	t.Run("no type of job, no check", func(t *testing.T) {
		jmv := NewJobMappingsValidator(mappings)
		jmv.ValidateTransformers(columns, foreignKeys, nil)
		require.Empty(t, jmv.GetColumnErrors())
	})
}

func Test_SupportedJobTypeOf(t *testing.T) {
	require.Equal(t, mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_UNSPECIFIED, SupportedJobTypeOf(nil))
	require.Equal(t, mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_SYNC, SupportedJobTypeOf(&mgmtv1alpha1.JobSource{
		Options: &mgmtv1alpha1.JobSourceOptions{Config: &mgmtv1alpha1.JobSourceOptions_Postgres{Postgres: &mgmtv1alpha1.PostgresSourceConnectionOptions{}}},
	}))
	require.Equal(t, mgmtv1alpha1.SupportedJobType_SUPPORTED_JOB_TYPE_GENERATE, SupportedJobTypeOf(&mgmtv1alpha1.JobSource{
		Options: &mgmtv1alpha1.JobSourceOptions{Config: &mgmtv1alpha1.JobSourceOptions_Generate{Generate: &mgmtv1alpha1.GenerateSourceOptions{}}},
	}))
}
