// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmgmt

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// GetUserBySub provides a mock function for the type MockInterface
func (_mock *MockInterface) GetUserBySub(ctx context.Context, sub string) (*User, error) {
	ret := _mock.Called(ctx, sub)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBySub")
	}

	var r0 *User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*User, error)); ok {
		return returnFunc(ctx, sub)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *User); ok {
		r0 = returnFunc(ctx, sub)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sub)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInterface_GetUserBySub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBySub'
type MockInterface_GetUserBySub_Call struct {
	*mock.Call
}

// GetUserBySub is a helper method to define mock.On call
//   - ctx context.Context
//   - sub string
func (_e *MockInterface_Expecter) GetUserBySub(ctx any, sub any) *MockInterface_GetUserBySub_Call {
	return &MockInterface_GetUserBySub_Call{Call: _e.mock.On("GetUserBySub", ctx, sub)}
}

func (_c *MockInterface_GetUserBySub_Call) Run(run func(ctx context.Context, sub string)) *MockInterface_GetUserBySub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInterface_GetUserBySub_Call) Return(user *User, err error) *MockInterface_GetUserBySub_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockInterface_GetUserBySub_Call) RunAndReturn(run func(ctx context.Context, sub string) (*User, error)) *MockInterface_GetUserBySub_Call {
	_c.Call.Return(run)
	return _c
}
