// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package awsmanager

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// NewMockdynamoDBAPIV2 creates a new instance of MockdynamoDBAPIV2. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockdynamoDBAPIV2(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockdynamoDBAPIV2 {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockdynamoDBAPIV2{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockdynamoDBAPIV2 is an autogenerated mock type for the dynamoDBAPIV2 type
type MockdynamoDBAPIV2 struct {
	mock.Mock
}

type MockdynamoDBAPIV2_Expecter struct {
	mock *mock.Mock
}

func (_m *MockdynamoDBAPIV2) EXPECT() *MockdynamoDBAPIV2_Expecter {
	return &MockdynamoDBAPIV2_Expecter{mock: &_m.Mock}
}

// DescribeTable provides a mock function for the type MockdynamoDBAPIV2
func (_mock *MockdynamoDBAPIV2) DescribeTable(ctx context.Context, params *dynamodb.DescribeTableInput, optFns ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]any, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DescribeTable")
	}

	var r0 *dynamodb.DescribeTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) *dynamodb.DescribeTableOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DescribeTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockdynamoDBAPIV2_DescribeTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeTable'
type MockdynamoDBAPIV2_DescribeTable_Call struct {
	*mock.Call
}

// DescribeTable is a helper method to define mock.On call
//   - ctx context.Context
//   - params *dynamodb.DescribeTableInput
//   - optFns ...func(*dynamodb.Options)
func (_e *MockdynamoDBAPIV2_Expecter) DescribeTable(ctx any, params any, optFns ...any) *MockdynamoDBAPIV2_DescribeTable_Call {
	return &MockdynamoDBAPIV2_DescribeTable_Call{Call: _e.mock.On("DescribeTable",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockdynamoDBAPIV2_DescribeTable_Call) Run(run func(ctx context.Context, params *dynamodb.DescribeTableInput, optFns ...func(*dynamodb.Options))) *MockdynamoDBAPIV2_DescribeTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DescribeTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DescribeTableInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockdynamoDBAPIV2_DescribeTable_Call) Return(describeTableOutput *dynamodb.DescribeTableOutput, err error) *MockdynamoDBAPIV2_DescribeTable_Call {
	_c.Call.Return(describeTableOutput, err)
	return _c
}

func (_c *MockdynamoDBAPIV2_DescribeTable_Call) RunAndReturn(run func(ctx context.Context, params *dynamodb.DescribeTableInput, optFns ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error)) *MockdynamoDBAPIV2_DescribeTable_Call {
	_c.Call.Return(run)
	return _c
}

// ListTables provides a mock function for the type MockdynamoDBAPIV2
func (_mock *MockdynamoDBAPIV2) ListTables(ctx context.Context, params *dynamodb.ListTablesInput, optFns ...func(*dynamodb.Options)) (*dynamodb.ListTablesOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]any, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListTables")
	}

	var r0 *dynamodb.ListTablesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ListTablesInput, ...func(*dynamodb.Options)) (*dynamodb.ListTablesOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ListTablesInput, ...func(*dynamodb.Options)) *dynamodb.ListTablesOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.ListTablesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.ListTablesInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockdynamoDBAPIV2_ListTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTables'
type MockdynamoDBAPIV2_ListTables_Call struct {
	*mock.Call
}

// ListTables is a helper method to define mock.On call
//   - ctx context.Context
//   - params *dynamodb.ListTablesInput
//   - optFns ...func(*dynamodb.Options)
func (_e *MockdynamoDBAPIV2_Expecter) ListTables(ctx any, params any, optFns ...any) *MockdynamoDBAPIV2_ListTables_Call {
	return &MockdynamoDBAPIV2_ListTables_Call{Call: _e.mock.On("ListTables",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockdynamoDBAPIV2_ListTables_Call) Run(run func(ctx context.Context, params *dynamodb.ListTablesInput, optFns ...func(*dynamodb.Options))) *MockdynamoDBAPIV2_ListTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.ListTablesInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.ListTablesInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockdynamoDBAPIV2_ListTables_Call) Return(listTablesOutput *dynamodb.ListTablesOutput, err error) *MockdynamoDBAPIV2_ListTables_Call {
	_c.Call.Return(listTablesOutput, err)
	return _c
}

func (_c *MockdynamoDBAPIV2_ListTables_Call) RunAndReturn(run func(ctx context.Context, params *dynamodb.ListTablesInput, optFns ...func(*dynamodb.Options)) (*dynamodb.ListTablesOutput, error)) *MockdynamoDBAPIV2_ListTables_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type MockdynamoDBAPIV2
func (_mock *MockdynamoDBAPIV2) Scan(ctx context.Context, params *dynamodb.ScanInput, optFns ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error) {
	// func(*dynamodb.Options)
	_va := make([]any, len(optFns))
	for _i := range optFns {
		_va[_i] = optFns[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, params)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 *dynamodb.ScanOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error)); ok {
		return returnFunc(ctx, params, optFns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) *dynamodb.ScanOutput); ok {
		r0 = returnFunc(ctx, params, optFns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.ScanOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, params, optFns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockdynamoDBAPIV2_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockdynamoDBAPIV2_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - params *dynamodb.ScanInput
//   - optFns ...func(*dynamodb.Options)
func (_e *MockdynamoDBAPIV2_Expecter) Scan(ctx any, params any, optFns ...any) *MockdynamoDBAPIV2_Scan_Call {
	return &MockdynamoDBAPIV2_Scan_Call{Call: _e.mock.On("Scan",
		append([]any{ctx, params}, optFns...)...)}
}

func (_c *MockdynamoDBAPIV2_Scan_Call) Run(run func(ctx context.Context, params *dynamodb.ScanInput, optFns ...func(*dynamodb.Options))) *MockdynamoDBAPIV2_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.ScanInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.ScanInput)
		}
		var arg2 []func(*dynamodb.Options)
		variadicArgs := make([]func(*dynamodb.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*dynamodb.Options))
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockdynamoDBAPIV2_Scan_Call) Return(scanOutput *dynamodb.ScanOutput, err error) *MockdynamoDBAPIV2_Scan_Call {
	_c.Call.Return(scanOutput, err)
	return _c
}

func (_c *MockdynamoDBAPIV2_Scan_Call) RunAndReturn(run func(ctx context.Context, params *dynamodb.ScanInput, optFns ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error)) *MockdynamoDBAPIV2_Scan_Call {
	_c.Call.Return(run)
	return _c
}
