package schema

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func Test_PostgresRenderer(t *testing.T) {
	table := &Table{
		Name: "COMMANDE",
		Columns: []Column{
			{Name: "id", Type: Uint64(), AutoIncrement: true},
			{Name: "order", Type: Varchar(20), Nullable: true, Collation: `"C"`},
			{Name: "parent_id", Type: Int64(), Default: "0"},
			{Name: "etat", Type: Native(map[Dialect]string{Postgres: "etat_enum"})},
			{Name: "total", Type: Int64(), Nullable: true, GeneratedAs: "parent_id * 2"},
		},
		PrimaryKey: []string{"id"},
		Indexes:    []Index{{Name: "uq_order", Columns: []string{"order"}, Unique: true}},
		ForeignKeys: []ForeignKey{
			{Name: "fk_parent", Columns: []string{"parent_id"}, RefTable: "COMMANDE", RefColumns: []string{"id"}, OnDelete: "CASCADE"},
			{Name: "fk_virtual", Columns: []string{"parent_id"}, RefTable: "COMMANDE", RefColumns: []string{"id"}, Virtual: true},
		},
	}
	r := PostgresRenderer{}

	create, err := r.CreateTable("bench_x", table)
	require.NoError(t, err)
	require.Equal(t, []string{
		"CREATE TABLE \"bench_x\".\"COMMANDE\" (\n" +
			"  \"id\" numeric(20,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
			"  \"order\" varchar(20) COLLATE \"C\",\n" +
			"  \"parent_id\" bigint NOT NULL DEFAULT 0,\n" +
			"  \"etat\" etat_enum NOT NULL,\n" +
			"  \"total\" bigint GENERATED ALWAYS AS (parent_id * 2) STORED,\n" +
			"  PRIMARY KEY (\"id\")\n" +
			")",
		"CREATE UNIQUE INDEX \"COMMANDE_uq_order\" ON \"bench_x\".\"COMMANDE\" (\"order\")",
	}, create, "PostgreSQL declares its indexes on their own, named per schema")

	require.Equal(t, []string{
		"ALTER TABLE \"bench_x\".\"COMMANDE\" ADD CONSTRAINT \"COMMANDE_fk_parent\" FOREIGN KEY (\"parent_id\") " +
			"REFERENCES \"bench_x\".\"COMMANDE\" (\"id\") ON DELETE CASCADE",
	}, r.AddForeignKeys("bench_x", table), "virtual foreign keys are not declared")

	require.Equal(t, []string{
		`DROP SCHEMA IF EXISTS "bench_x" CASCADE`,
		`CREATE SCHEMA "bench_x"`,
	}, r.CreateContainerStatements("bench_x"), "a case is a schema, not a database")
}

func Test_PostgresRenderer_refusesWhatItHasNo(t *testing.T) {
	for name, column := range map[string]Column{
		"on update":       {Name: "c", Type: Int64(), OnUpdate: "CURRENT_TIMESTAMP"},
		"invisible":       {Name: "c", Type: Int64(), Invisible: true},
		"native for none": {Name: "c", Type: Native(map[Dialect]string{MySQL: "SET('a')"})},
	} {
		t.Run(name, func(t *testing.T) {
			_, err := PostgresRenderer{}.CreateTable("bench_x", &Table{Name: "T", Columns: []Column{column}})
			require.Error(t, err, "a case asking for what PostgreSQL has not must say so, not be rendered into something else")
		})
	}
}
