// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mssql_queries

import (
	"context"

	"github.com/fishtre-compagnie/husonym/backend/gen/go/db/dbschemas/mysql"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// GetAllSchemas provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetAllSchemas(ctx context.Context, db mysql_queries.DBTX) ([]string, error) {
	ret := _mock.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for GetAllSchemas")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX) ([]string, error)); ok {
		return returnFunc(ctx, db)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX) []string); ok {
		r0 = returnFunc(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX) error); ok {
		r1 = returnFunc(ctx, db)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetAllSchemas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSchemas'
type MockQuerier_GetAllSchemas_Call struct {
	*mock.Call
}

// GetAllSchemas is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
func (_e *MockQuerier_Expecter) GetAllSchemas(ctx any, db any) *MockQuerier_GetAllSchemas_Call {
	return &MockQuerier_GetAllSchemas_Call{Call: _e.mock.On("GetAllSchemas", ctx, db)}
}

func (_c *MockQuerier_GetAllSchemas_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX)) *MockQuerier_GetAllSchemas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetAllSchemas_Call) Return(strings []string, err error) *MockQuerier_GetAllSchemas_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockQuerier_GetAllSchemas_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX) ([]string, error)) *MockQuerier_GetAllSchemas_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTables provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetAllTables(ctx context.Context, db mysql_queries.DBTX) ([]*GetAllTablesRow, error) {
	ret := _mock.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTables")
	}

	var r0 []*GetAllTablesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX) ([]*GetAllTablesRow, error)); ok {
		return returnFunc(ctx, db)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX) []*GetAllTablesRow); ok {
		r0 = returnFunc(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetAllTablesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX) error); ok {
		r1 = returnFunc(ctx, db)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetAllTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTables'
type MockQuerier_GetAllTables_Call struct {
	*mock.Call
}

// GetAllTables is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
func (_e *MockQuerier_Expecter) GetAllTables(ctx any, db any) *MockQuerier_GetAllTables_Call {
	return &MockQuerier_GetAllTables_Call{Call: _e.mock.On("GetAllTables", ctx, db)}
}

func (_c *MockQuerier_GetAllTables_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX)) *MockQuerier_GetAllTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetAllTables_Call) Return(getAllTablesRows []*GetAllTablesRow, err error) *MockQuerier_GetAllTables_Call {
	_c.Call.Return(getAllTablesRows, err)
	return _c
}

func (_c *MockQuerier_GetAllTables_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX) ([]*GetAllTablesRow, error)) *MockQuerier_GetAllTables_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomSequencesBySchemas provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetCustomSequencesBySchemas(ctx context.Context, db mysql_queries.DBTX, schemas []string) ([]*GetCustomSequencesBySchemasRow, error) {
	ret := _mock.Called(ctx, db, schemas)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomSequencesBySchemas")
	}

	var r0 []*GetCustomSequencesBySchemasRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) ([]*GetCustomSequencesBySchemasRow, error)); ok {
		return returnFunc(ctx, db, schemas)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) []*GetCustomSequencesBySchemasRow); ok {
		r0 = returnFunc(ctx, db, schemas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetCustomSequencesBySchemasRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX, []string) error); ok {
		r1 = returnFunc(ctx, db, schemas)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetCustomSequencesBySchemas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomSequencesBySchemas'
type MockQuerier_GetCustomSequencesBySchemas_Call struct {
	*mock.Call
}

// GetCustomSequencesBySchemas is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
//   - schemas []string
func (_e *MockQuerier_Expecter) GetCustomSequencesBySchemas(ctx any, db any, schemas any) *MockQuerier_GetCustomSequencesBySchemas_Call {
	return &MockQuerier_GetCustomSequencesBySchemas_Call{Call: _e.mock.On("GetCustomSequencesBySchemas", ctx, db, schemas)}
}

func (_c *MockQuerier_GetCustomSequencesBySchemas_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX, schemas []string)) *MockQuerier_GetCustomSequencesBySchemas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetCustomSequencesBySchemas_Call) Return(getCustomSequencesBySchemasRows []*GetCustomSequencesBySchemasRow, err error) *MockQuerier_GetCustomSequencesBySchemas_Call {
	_c.Call.Return(getCustomSequencesBySchemasRows, err)
	return _c
}

func (_c *MockQuerier_GetCustomSequencesBySchemas_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX, schemas []string) ([]*GetCustomSequencesBySchemasRow, error)) *MockQuerier_GetCustomSequencesBySchemas_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomTriggersBySchemasAndTables provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetCustomTriggersBySchemasAndTables(ctx context.Context, db mysql_queries.DBTX, schematables []string) ([]*GetCustomTriggersBySchemasAndTablesRow, error) {
	ret := _mock.Called(ctx, db, schematables)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomTriggersBySchemasAndTables")
	}

	var r0 []*GetCustomTriggersBySchemasAndTablesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) ([]*GetCustomTriggersBySchemasAndTablesRow, error)); ok {
		return returnFunc(ctx, db, schematables)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) []*GetCustomTriggersBySchemasAndTablesRow); ok {
		r0 = returnFunc(ctx, db, schematables)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetCustomTriggersBySchemasAndTablesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX, []string) error); ok {
		r1 = returnFunc(ctx, db, schematables)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetCustomTriggersBySchemasAndTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomTriggersBySchemasAndTables'
type MockQuerier_GetCustomTriggersBySchemasAndTables_Call struct {
	*mock.Call
}

// GetCustomTriggersBySchemasAndTables is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
//   - schematables []string
func (_e *MockQuerier_Expecter) GetCustomTriggersBySchemasAndTables(ctx any, db any, schematables any) *MockQuerier_GetCustomTriggersBySchemasAndTables_Call {
	return &MockQuerier_GetCustomTriggersBySchemasAndTables_Call{Call: _e.mock.On("GetCustomTriggersBySchemasAndTables", ctx, db, schematables)}
}

func (_c *MockQuerier_GetCustomTriggersBySchemasAndTables_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX, schematables []string)) *MockQuerier_GetCustomTriggersBySchemasAndTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetCustomTriggersBySchemasAndTables_Call) Return(getCustomTriggersBySchemasAndTablesRows []*GetCustomTriggersBySchemasAndTablesRow, err error) *MockQuerier_GetCustomTriggersBySchemasAndTables_Call {
	_c.Call.Return(getCustomTriggersBySchemasAndTablesRows, err)
	return _c
}

func (_c *MockQuerier_GetCustomTriggersBySchemasAndTables_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX, schematables []string) ([]*GetCustomTriggersBySchemasAndTablesRow, error)) *MockQuerier_GetCustomTriggersBySchemasAndTables_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataTypesBySchemas provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDataTypesBySchemas(ctx context.Context, db mysql_queries.DBTX, schematables []string) ([]*GetDataTypesBySchemasRow, error) {
	ret := _mock.Called(ctx, db, schematables)

	if len(ret) == 0 {
		panic("no return value specified for GetDataTypesBySchemas")
	}

	var r0 []*GetDataTypesBySchemasRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) ([]*GetDataTypesBySchemasRow, error)); ok {
		return returnFunc(ctx, db, schematables)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) []*GetDataTypesBySchemasRow); ok {
		r0 = returnFunc(ctx, db, schematables)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetDataTypesBySchemasRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX, []string) error); ok {
		r1 = returnFunc(ctx, db, schematables)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDataTypesBySchemas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataTypesBySchemas'
type MockQuerier_GetDataTypesBySchemas_Call struct {
	*mock.Call
}

// GetDataTypesBySchemas is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
//   - schematables []string
func (_e *MockQuerier_Expecter) GetDataTypesBySchemas(ctx any, db any, schematables any) *MockQuerier_GetDataTypesBySchemas_Call {
	return &MockQuerier_GetDataTypesBySchemas_Call{Call: _e.mock.On("GetDataTypesBySchemas", ctx, db, schematables)}
}

func (_c *MockQuerier_GetDataTypesBySchemas_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX, schematables []string)) *MockQuerier_GetDataTypesBySchemas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDataTypesBySchemas_Call) Return(getDataTypesBySchemasRows []*GetDataTypesBySchemasRow, err error) *MockQuerier_GetDataTypesBySchemas_Call {
	_c.Call.Return(getDataTypesBySchemasRows, err)
	return _c
}

func (_c *MockQuerier_GetDataTypesBySchemas_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX, schematables []string) ([]*GetDataTypesBySchemasRow, error)) *MockQuerier_GetDataTypesBySchemas_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseSchema provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseSchema(ctx context.Context, db mysql_queries.DBTX) ([]*GetDatabaseSchemaRow, error) {
	ret := _mock.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseSchema")
	}

	var r0 []*GetDatabaseSchemaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX) ([]*GetDatabaseSchemaRow, error)); ok {
		return returnFunc(ctx, db)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX) []*GetDatabaseSchemaRow); ok {
		r0 = returnFunc(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetDatabaseSchemaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX) error); ok {
		r1 = returnFunc(ctx, db)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseSchema'
type MockQuerier_GetDatabaseSchema_Call struct {
	*mock.Call
}

// GetDatabaseSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
func (_e *MockQuerier_Expecter) GetDatabaseSchema(ctx any, db any) *MockQuerier_GetDatabaseSchema_Call {
	return &MockQuerier_GetDatabaseSchema_Call{Call: _e.mock.On("GetDatabaseSchema", ctx, db)}
}

func (_c *MockQuerier_GetDatabaseSchema_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX)) *MockQuerier_GetDatabaseSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseSchema_Call) Return(getDatabaseSchemaRows []*GetDatabaseSchemaRow, err error) *MockQuerier_GetDatabaseSchema_Call {
	_c.Call.Return(getDatabaseSchemaRows, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseSchema_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX) ([]*GetDatabaseSchemaRow, error)) *MockQuerier_GetDatabaseSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseTableSchemasBySchemasAndTables provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetDatabaseTableSchemasBySchemasAndTables(ctx context.Context, db mysql_queries.DBTX, schematables []string) ([]*GetDatabaseSchemaRow, error) {
	ret := _mock.Called(ctx, db, schematables)

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseTableSchemasBySchemasAndTables")
	}

	var r0 []*GetDatabaseSchemaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) ([]*GetDatabaseSchemaRow, error)); ok {
		return returnFunc(ctx, db, schematables)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) []*GetDatabaseSchemaRow); ok {
		r0 = returnFunc(ctx, db, schematables)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetDatabaseSchemaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX, []string) error); ok {
		r1 = returnFunc(ctx, db, schematables)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseTableSchemasBySchemasAndTables'
type MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call struct {
	*mock.Call
}

// GetDatabaseTableSchemasBySchemasAndTables is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
//   - schematables []string
func (_e *MockQuerier_Expecter) GetDatabaseTableSchemasBySchemasAndTables(ctx any, db any, schematables any) *MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call {
	return &MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call{Call: _e.mock.On("GetDatabaseTableSchemasBySchemasAndTables", ctx, db, schematables)}
}

func (_c *MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX, schematables []string)) *MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call) Return(getDatabaseSchemaRows []*GetDatabaseSchemaRow, err error) *MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call {
	_c.Call.Return(getDatabaseSchemaRows, err)
	return _c
}

func (_c *MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX, schematables []string) ([]*GetDatabaseSchemaRow, error)) *MockQuerier_GetDatabaseTableSchemasBySchemasAndTables_Call {
	_c.Call.Return(run)
	return _c
}

// GetIndicesBySchemasAndTables provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetIndicesBySchemasAndTables(ctx context.Context, db mysql_queries.DBTX, schematables []string) ([]*GetIndicesBySchemasAndTablesRow, error) {
	ret := _mock.Called(ctx, db, schematables)

	if len(ret) == 0 {
		panic("no return value specified for GetIndicesBySchemasAndTables")
	}

	var r0 []*GetIndicesBySchemasAndTablesRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) ([]*GetIndicesBySchemasAndTablesRow, error)); ok {
		return returnFunc(ctx, db, schematables)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) []*GetIndicesBySchemasAndTablesRow); ok {
		r0 = returnFunc(ctx, db, schematables)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetIndicesBySchemasAndTablesRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX, []string) error); ok {
		r1 = returnFunc(ctx, db, schematables)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetIndicesBySchemasAndTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIndicesBySchemasAndTables'
type MockQuerier_GetIndicesBySchemasAndTables_Call struct {
	*mock.Call
}

// GetIndicesBySchemasAndTables is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
//   - schematables []string
func (_e *MockQuerier_Expecter) GetIndicesBySchemasAndTables(ctx any, db any, schematables any) *MockQuerier_GetIndicesBySchemasAndTables_Call {
	return &MockQuerier_GetIndicesBySchemasAndTables_Call{Call: _e.mock.On("GetIndicesBySchemasAndTables", ctx, db, schematables)}
}

func (_c *MockQuerier_GetIndicesBySchemasAndTables_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX, schematables []string)) *MockQuerier_GetIndicesBySchemasAndTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetIndicesBySchemasAndTables_Call) Return(getIndicesBySchemasAndTablesRows []*GetIndicesBySchemasAndTablesRow, err error) *MockQuerier_GetIndicesBySchemasAndTables_Call {
	_c.Call.Return(getIndicesBySchemasAndTablesRows, err)
	return _c
}

func (_c *MockQuerier_GetIndicesBySchemasAndTables_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX, schematables []string) ([]*GetIndicesBySchemasAndTablesRow, error)) *MockQuerier_GetIndicesBySchemasAndTables_Call {
	_c.Call.Return(run)
	return _c
}

// GetRolePermissions provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetRolePermissions(ctx context.Context, db mysql_queries.DBTX) ([]*GetRolePermissionsRow, error) {
	ret := _mock.Called(ctx, db)

	if len(ret) == 0 {
		panic("no return value specified for GetRolePermissions")
	}

	var r0 []*GetRolePermissionsRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX) ([]*GetRolePermissionsRow, error)); ok {
		return returnFunc(ctx, db)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX) []*GetRolePermissionsRow); ok {
		r0 = returnFunc(ctx, db)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetRolePermissionsRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX) error); ok {
		r1 = returnFunc(ctx, db)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetRolePermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolePermissions'
type MockQuerier_GetRolePermissions_Call struct {
	*mock.Call
}

// GetRolePermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
func (_e *MockQuerier_Expecter) GetRolePermissions(ctx any, db any) *MockQuerier_GetRolePermissions_Call {
	return &MockQuerier_GetRolePermissions_Call{Call: _e.mock.On("GetRolePermissions", ctx, db)}
}

func (_c *MockQuerier_GetRolePermissions_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX)) *MockQuerier_GetRolePermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetRolePermissions_Call) Return(getRolePermissionsRows []*GetRolePermissionsRow, err error) *MockQuerier_GetRolePermissions_Call {
	_c.Call.Return(getRolePermissionsRows, err)
	return _c
}

func (_c *MockQuerier_GetRolePermissions_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX) ([]*GetRolePermissionsRow, error)) *MockQuerier_GetRolePermissions_Call {
	_c.Call.Return(run)
	return _c
}

// GetTableConstraintsBySchemas provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetTableConstraintsBySchemas(ctx context.Context, db mysql_queries.DBTX, schemas []string) ([]*GetTableConstraintsBySchemasRow, error) {
	ret := _mock.Called(ctx, db, schemas)

	if len(ret) == 0 {
		panic("no return value specified for GetTableConstraintsBySchemas")
	}

	var r0 []*GetTableConstraintsBySchemasRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) ([]*GetTableConstraintsBySchemasRow, error)); ok {
		return returnFunc(ctx, db, schemas)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) []*GetTableConstraintsBySchemasRow); ok {
		r0 = returnFunc(ctx, db, schemas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetTableConstraintsBySchemasRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX, []string) error); ok {
		r1 = returnFunc(ctx, db, schemas)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetTableConstraintsBySchemas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTableConstraintsBySchemas'
type MockQuerier_GetTableConstraintsBySchemas_Call struct {
	*mock.Call
}

// GetTableConstraintsBySchemas is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
//   - schemas []string
func (_e *MockQuerier_Expecter) GetTableConstraintsBySchemas(ctx any, db any, schemas any) *MockQuerier_GetTableConstraintsBySchemas_Call {
	return &MockQuerier_GetTableConstraintsBySchemas_Call{Call: _e.mock.On("GetTableConstraintsBySchemas", ctx, db, schemas)}
}

func (_c *MockQuerier_GetTableConstraintsBySchemas_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX, schemas []string)) *MockQuerier_GetTableConstraintsBySchemas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetTableConstraintsBySchemas_Call) Return(getTableConstraintsBySchemasRows []*GetTableConstraintsBySchemasRow, err error) *MockQuerier_GetTableConstraintsBySchemas_Call {
	_c.Call.Return(getTableConstraintsBySchemasRows, err)
	return _c
}

func (_c *MockQuerier_GetTableConstraintsBySchemas_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX, schemas []string) ([]*GetTableConstraintsBySchemasRow, error)) *MockQuerier_GetTableConstraintsBySchemas_Call {
	_c.Call.Return(run)
	return _c
}

// GetUniqueIndexesBySchema provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUniqueIndexesBySchema(ctx context.Context, db mysql_queries.DBTX, schemas []string) ([]*GetUniqueIndexesBySchemaRow, error) {
	ret := _mock.Called(ctx, db, schemas)

	if len(ret) == 0 {
		panic("no return value specified for GetUniqueIndexesBySchema")
	}

	var r0 []*GetUniqueIndexesBySchemaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) ([]*GetUniqueIndexesBySchemaRow, error)); ok {
		return returnFunc(ctx, db, schemas)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) []*GetUniqueIndexesBySchemaRow); ok {
		r0 = returnFunc(ctx, db, schemas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetUniqueIndexesBySchemaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX, []string) error); ok {
		r1 = returnFunc(ctx, db, schemas)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUniqueIndexesBySchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUniqueIndexesBySchema'
type MockQuerier_GetUniqueIndexesBySchema_Call struct {
	*mock.Call
}

// GetUniqueIndexesBySchema is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
//   - schemas []string
func (_e *MockQuerier_Expecter) GetUniqueIndexesBySchema(ctx any, db any, schemas any) *MockQuerier_GetUniqueIndexesBySchema_Call {
	return &MockQuerier_GetUniqueIndexesBySchema_Call{Call: _e.mock.On("GetUniqueIndexesBySchema", ctx, db, schemas)}
}

func (_c *MockQuerier_GetUniqueIndexesBySchema_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX, schemas []string)) *MockQuerier_GetUniqueIndexesBySchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUniqueIndexesBySchema_Call) Return(getUniqueIndexesBySchemaRows []*GetUniqueIndexesBySchemaRow, err error) *MockQuerier_GetUniqueIndexesBySchema_Call {
	_c.Call.Return(getUniqueIndexesBySchemaRows, err)
	return _c
}

func (_c *MockQuerier_GetUniqueIndexesBySchema_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX, schemas []string) ([]*GetUniqueIndexesBySchemaRow, error)) *MockQuerier_GetUniqueIndexesBySchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetViewsAndFunctionsBySchemas provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetViewsAndFunctionsBySchemas(ctx context.Context, db mysql_queries.DBTX, schemas []string) ([]*GetViewsAndFunctionsBySchemasRow, error) {
	ret := _mock.Called(ctx, db, schemas)

	if len(ret) == 0 {
		panic("no return value specified for GetViewsAndFunctionsBySchemas")
	}

	var r0 []*GetViewsAndFunctionsBySchemasRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) ([]*GetViewsAndFunctionsBySchemasRow, error)); ok {
		return returnFunc(ctx, db, schemas)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, mysql_queries.DBTX, []string) []*GetViewsAndFunctionsBySchemasRow); ok {
		r0 = returnFunc(ctx, db, schemas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*GetViewsAndFunctionsBySchemasRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, mysql_queries.DBTX, []string) error); ok {
		r1 = returnFunc(ctx, db, schemas)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetViewsAndFunctionsBySchemas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetViewsAndFunctionsBySchemas'
type MockQuerier_GetViewsAndFunctionsBySchemas_Call struct {
	*mock.Call
}

// GetViewsAndFunctionsBySchemas is a helper method to define mock.On call
//   - ctx context.Context
//   - db mysql_queries.DBTX
//   - schemas []string
func (_e *MockQuerier_Expecter) GetViewsAndFunctionsBySchemas(ctx any, db any, schemas any) *MockQuerier_GetViewsAndFunctionsBySchemas_Call {
	return &MockQuerier_GetViewsAndFunctionsBySchemas_Call{Call: _e.mock.On("GetViewsAndFunctionsBySchemas", ctx, db, schemas)}
}

func (_c *MockQuerier_GetViewsAndFunctionsBySchemas_Call) Run(run func(ctx context.Context, db mysql_queries.DBTX, schemas []string)) *MockQuerier_GetViewsAndFunctionsBySchemas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mysql_queries.DBTX
		if args[1] != nil {
			arg1 = args[1].(mysql_queries.DBTX)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuerier_GetViewsAndFunctionsBySchemas_Call) Return(getViewsAndFunctionsBySchemasRows []*GetViewsAndFunctionsBySchemasRow, err error) *MockQuerier_GetViewsAndFunctionsBySchemas_Call {
	_c.Call.Return(getViewsAndFunctionsBySchemasRows, err)
	return _c
}

func (_c *MockQuerier_GetViewsAndFunctionsBySchemas_Call) RunAndReturn(run func(ctx context.Context, db mysql_queries.DBTX, schemas []string) ([]*GetViewsAndFunctionsBySchemasRow, error)) *MockQuerier_GetViewsAndFunctionsBySchemas_Call {
	_c.Call.Return(run)
	return _c
}
