# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mgmt.v1alpha1 import usage_pb2 as mgmt_dot_v1alpha1_dot_usage__pb2


class UsageServiceStub:
    """Holds the counters of what the instance runs.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordRunStarted = channel.unary_unary(
                '/mgmt.v1alpha1.UsageService/RecordRunStarted',
                request_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunStartedRequest.SerializeToString,
                response_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunStartedResponse.FromString,
                _registered_method=True)
        self.RecordRunEnded = channel.unary_unary(
                '/mgmt.v1alpha1.UsageService/RecordRunEnded',
                request_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunEndedRequest.SerializeToString,
                response_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunEndedResponse.FromString,
                _registered_method=True)
        self.GetUsageReporting = channel.unary_unary(
                '/mgmt.v1alpha1.UsageService/GetUsageReporting',
                request_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportingRequest.SerializeToString,
                response_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportingResponse.FromString,
                _registered_method=True)
        self.GetUsageReport = channel.unary_unary(
                '/mgmt.v1alpha1.UsageService/GetUsageReport',
                request_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportRequest.SerializeToString,
                response_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportResponse.FromString,
                _registered_method=True)
        self.GetUsagePeriodReport = channel.unary_unary(
                '/mgmt.v1alpha1.UsageService/GetUsagePeriodReport',
                request_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsagePeriodReportRequest.SerializeToString,
                response_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsagePeriodReportResponse.FromString,
                _registered_method=True)
        self.GetAccountUsage = channel.unary_unary(
                '/mgmt.v1alpha1.UsageService/GetAccountUsage',
                request_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetAccountUsageRequest.SerializeToString,
                response_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetAccountUsageResponse.FromString,
                _registered_method=True)
        self.GetJobUsage = channel.unary_unary(
                '/mgmt.v1alpha1.UsageService/GetJobUsage',
                request_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetJobUsageRequest.SerializeToString,
                response_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetJobUsageResponse.FromString,
                _registered_method=True)


class UsageServiceServicer:
    """Holds the counters of what the instance runs.
    """

    def RecordRunStarted(self, request, context):
        """Tells that a run has begun. Only the worker calls this, with its key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordRunEnded(self, request, context):
        """Tells that a run has ended, and what it did. Only the worker calls this, with its key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageReporting(self, request, context):
        """Tells under which mode the usage report of the instance is sent, and what became of the reports of the last 30 days.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsageReport(self, request, context):
        """Gives the usage report of a day, as it is kept.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsagePeriodReport(self, request, context):
        """Makes the usage report of the instance for a period of months, month by month, and seals it. Needs a license key in force.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountUsage(self, request, context):
        """Gives what the runs of an account add up to over a period of days: its totals, its days, its jobs, its errors and what the license refused it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobUsage(self, request, context):
        """Gives what the runs of a job of an account add up to over a period of days, and the latest of them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordRunStarted': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordRunStarted,
                    request_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunStartedRequest.FromString,
                    response_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunStartedResponse.SerializeToString,
            ),
            'RecordRunEnded': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordRunEnded,
                    request_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunEndedRequest.FromString,
                    response_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunEndedResponse.SerializeToString,
            ),
            'GetUsageReporting': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageReporting,
                    request_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportingRequest.FromString,
                    response_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportingResponse.SerializeToString,
            ),
            'GetUsageReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsageReport,
                    request_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportRequest.FromString,
                    response_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportResponse.SerializeToString,
            ),
            'GetUsagePeriodReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsagePeriodReport,
                    request_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsagePeriodReportRequest.FromString,
                    response_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetUsagePeriodReportResponse.SerializeToString,
            ),
            'GetAccountUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountUsage,
                    request_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetAccountUsageRequest.FromString,
                    response_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetAccountUsageResponse.SerializeToString,
            ),
            'GetJobUsage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobUsage,
                    request_deserializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetJobUsageRequest.FromString,
                    response_serializer=mgmt_dot_v1alpha1_dot_usage__pb2.GetJobUsageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mgmt.v1alpha1.UsageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mgmt.v1alpha1.UsageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UsageService:
    """Holds the counters of what the instance runs.
    """

    @staticmethod
    def RecordRunStarted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mgmt.v1alpha1.UsageService/RecordRunStarted',
            mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunStartedRequest.SerializeToString,
            mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunStartedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordRunEnded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mgmt.v1alpha1.UsageService/RecordRunEnded',
            mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunEndedRequest.SerializeToString,
            mgmt_dot_v1alpha1_dot_usage__pb2.RecordRunEndedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageReporting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mgmt.v1alpha1.UsageService/GetUsageReporting',
            mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportingRequest.SerializeToString,
            mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsageReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mgmt.v1alpha1.UsageService/GetUsageReport',
            mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportRequest.SerializeToString,
            mgmt_dot_v1alpha1_dot_usage__pb2.GetUsageReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsagePeriodReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mgmt.v1alpha1.UsageService/GetUsagePeriodReport',
            mgmt_dot_v1alpha1_dot_usage__pb2.GetUsagePeriodReportRequest.SerializeToString,
            mgmt_dot_v1alpha1_dot_usage__pb2.GetUsagePeriodReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mgmt.v1alpha1.UsageService/GetAccountUsage',
            mgmt_dot_v1alpha1_dot_usage__pb2.GetAccountUsageRequest.SerializeToString,
            mgmt_dot_v1alpha1_dot_usage__pb2.GetAccountUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobUsage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mgmt.v1alpha1.UsageService/GetJobUsage',
            mgmt_dot_v1alpha1_dot_usage__pb2.GetJobUsageRequest.SerializeToString,
            mgmt_dot_v1alpha1_dot_usage__pb2.GetJobUsageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
