// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clientcredtokenprovider

import (
	"context"

	"github.com/fishtre-compagnie/husonym/backend/internal/auth/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMocktokenProvider creates a new instance of MocktokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktokenProvider {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MocktokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MocktokenProvider is an autogenerated mock type for the tokenProvider type
type MocktokenProvider struct {
	mock.Mock
}

type MocktokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MocktokenProvider) EXPECT() *MocktokenProvider_Expecter {
	return &MocktokenProvider_Expecter{mock: &_m.Mock}
}

// GetToken provides a mock function for the type MocktokenProvider
func (_mock *MocktokenProvider) GetToken(context1 context.Context) (*auth_client.AuthTokenResponse, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 *auth_client.AuthTokenResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*auth_client.AuthTokenResponse, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *auth_client.AuthTokenResponse); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth_client.AuthTokenResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MocktokenProvider_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MocktokenProvider_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MocktokenProvider_Expecter) GetToken(context1 any) *MocktokenProvider_GetToken_Call {
	return &MocktokenProvider_GetToken_Call{Call: _e.mock.On("GetToken", context1)}
}

func (_c *MocktokenProvider_GetToken_Call) Run(run func(context1 context.Context)) *MocktokenProvider_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MocktokenProvider_GetToken_Call) Return(authTokenResponse *auth_client.AuthTokenResponse, err error) *MocktokenProvider_GetToken_Call {
	_c.Call.Return(authTokenResponse, err)
	return _c
}

func (_c *MocktokenProvider_GetToken_Call) RunAndReturn(run func(context1 context.Context) (*auth_client.AuthTokenResponse, error)) *MocktokenProvider_GetToken_Call {
	_c.Call.Return(run)
	return _c
}
