// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=.js"
// @generated from file mgmt/v1alpha1/usage.proto (package mgmt.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_mgmt_v1alpha1_permission } from "./permission_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file mgmt/v1alpha1/usage.proto.
 */
export const file_mgmt_v1alpha1_usage: GenFile = /*@__PURE__*/
  fileDesc("ChltZ210L3YxYWxwaGExL3VzYWdlLnByb3RvEg1tZ210LnYxYWxwaGExIoQBChdSZWNvcmRSdW5TdGFydGVkUmVxdWVzdBIYCgZqb2JfaWQYASABKAlCCLpIBXIDsAEBEhcKBnJ1bl9pZBgCIAEoCUIHukgEcgIQARI2CgpzdGFydGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIGukgDyAEBIhoKGFJlY29yZFJ1blN0YXJ0ZWRSZXNwb25zZSLHAgoVUmVjb3JkUnVuRW5kZWRSZXF1ZXN0EhgKBmpvYl9pZBgBIAEoCUIIukgFcgOwAQESFwoGcnVuX2lkGAIgASgJQge6SARyAhABEjYKCnN0YXJ0ZWRfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQga6SAPIAQESNAoIZW5kZWRfYXQYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQga6SAPIAQESNgoHb3V0Y29tZRgFIAEoDjIZLm1nbXQudjFhbHBoYTEuUnVuT3V0Y29tZUIKukgHggEEEAEgABIaCglyb3dzX3JlYWQYBiABKANCB7pIBCICKAASHwoOcm93c19kaXNjYXJkZWQYByABKANCB7pIBCICKAASGAoHcmV0cmllcxgIIAEoA0IHukgEIgIoACIYChZSZWNvcmRSdW5FbmRlZFJlc3BvbnNlKnYKClJ1bk91dGNvbWUSGwoXUlVOX09VVENPTUVfVU5TUEVDSUZJRUQQABIZChVSVU5fT1VUQ09NRV9DT01QTEVURUQQARIWChJSVU5fT1VUQ09NRV9GQUlMRUQQAhIYChRSVU5fT1VUQ09NRV9DQU5DRUxFRBADMuIBCgxVc2FnZVNlcnZpY2USawoQUmVjb3JkUnVuU3RhcnRlZBImLm1nbXQudjFhbHBoYTEuUmVjb3JkUnVuU3RhcnRlZFJlcXVlc3QaJy5tZ210LnYxYWxwaGExLlJlY29yZFJ1blN0YXJ0ZWRSZXNwb25zZSIGkrUYAhABEmUKDlJlY29yZFJ1bkVuZGVkEiQubWdtdC52MWFscGhhMS5SZWNvcmRSdW5FbmRlZFJlcXVlc3QaJS5tZ210LnYxYWxwaGExLlJlY29yZFJ1bkVuZGVkUmVzcG9uc2UiBpK1GAIQAULLAQoRY29tLm1nbXQudjFhbHBoYTFCClVzYWdlUHJvdG9QAVpVZ2l0aHViLmNvbS9maXNodHJlLWNvbXBhZ25pZS9odXNvbnltL2JhY2tlbmQvZ2VuL2dvL3Byb3Rvcy9tZ210L3YxYWxwaGExO21nbXR2MWFscGhhMaICA01YWKoCDU1nbXQuVjFhbHBoYTHKAg1NZ210XFYxYWxwaGEx4gIZTWdtdFxWMWFscGhhMVxHUEJNZXRhZGF0YeoCDk1nbXQ6OlYxYWxwaGExYgZwcm90bzM", [file_buf_validate_validate, file_google_protobuf_timestamp, file_mgmt_v1alpha1_permission]);

/**
 * @generated from message mgmt.v1alpha1.RecordRunStartedRequest
 */
export type RecordRunStartedRequest = Message<"mgmt.v1alpha1.RecordRunStartedRequest"> & {
  /**
   * The job the run belongs to. The account and the kind of the run are read from it.
   *
   * @generated from field: string job_id = 1;
   */
  jobId: string;

  /**
   * The identifier of the run, as the orchestrator gives it.
   *
   * @generated from field: string run_id = 2;
   */
  runId: string;

  /**
   * When the run began.
   *
   * @generated from field: google.protobuf.Timestamp started_at = 3;
   */
  startedAt?: Timestamp | undefined;
};

/**
 * Describes the message mgmt.v1alpha1.RecordRunStartedRequest.
 * Use `create(RecordRunStartedRequestSchema)` to create a new message.
 */
export const RecordRunStartedRequestSchema: GenMessage<RecordRunStartedRequest> = /*@__PURE__*/
  messageDesc(file_mgmt_v1alpha1_usage, 0);

/**
 * @generated from message mgmt.v1alpha1.RecordRunStartedResponse
 */
export type RecordRunStartedResponse = Message<"mgmt.v1alpha1.RecordRunStartedResponse"> & {
};

/**
 * Describes the message mgmt.v1alpha1.RecordRunStartedResponse.
 * Use `create(RecordRunStartedResponseSchema)` to create a new message.
 */
export const RecordRunStartedResponseSchema: GenMessage<RecordRunStartedResponse> = /*@__PURE__*/
  messageDesc(file_mgmt_v1alpha1_usage, 1);

/**
 * @generated from message mgmt.v1alpha1.RecordRunEndedRequest
 */
export type RecordRunEndedRequest = Message<"mgmt.v1alpha1.RecordRunEndedRequest"> & {
  /**
   * The job the run belongs to. The account and the kind of the run are read from it.
   *
   * @generated from field: string job_id = 1;
   */
  jobId: string;

  /**
   * The identifier of the run, as the orchestrator gives it.
   *
   * @generated from field: string run_id = 2;
   */
  runId: string;

  /**
   * When the run began.
   *
   * @generated from field: google.protobuf.Timestamp started_at = 3;
   */
  startedAt?: Timestamp | undefined;

  /**
   * When the run ended.
   *
   * @generated from field: google.protobuf.Timestamp ended_at = 4;
   */
  endedAt?: Timestamp | undefined;

  /**
   * How the run ended.
   *
   * @generated from field: mgmt.v1alpha1.RunOutcome outcome = 5;
   */
  outcome: RunOutcome;

  /**
   * The rows the run read from its source.
   *
   * @generated from field: int64 rows_read = 6;
   */
  rowsRead: bigint;

  /**
   * The rows the run set aside instead of writing them.
   *
   * @generated from field: int64 rows_discarded = 7;
   */
  rowsDiscarded: bigint;

  /**
   * The times the run's activities were tried again.
   *
   * @generated from field: int64 retries = 8;
   */
  retries: bigint;
};

/**
 * Describes the message mgmt.v1alpha1.RecordRunEndedRequest.
 * Use `create(RecordRunEndedRequestSchema)` to create a new message.
 */
export const RecordRunEndedRequestSchema: GenMessage<RecordRunEndedRequest> = /*@__PURE__*/
  messageDesc(file_mgmt_v1alpha1_usage, 2);

/**
 * @generated from message mgmt.v1alpha1.RecordRunEndedResponse
 */
export type RecordRunEndedResponse = Message<"mgmt.v1alpha1.RecordRunEndedResponse"> & {
};

/**
 * Describes the message mgmt.v1alpha1.RecordRunEndedResponse.
 * Use `create(RecordRunEndedResponseSchema)` to create a new message.
 */
export const RecordRunEndedResponseSchema: GenMessage<RecordRunEndedResponse> = /*@__PURE__*/
  messageDesc(file_mgmt_v1alpha1_usage, 3);

/**
 * How a run ended.
 *
 * @generated from enum mgmt.v1alpha1.RunOutcome
 */
export enum RunOutcome {
  /**
   * @generated from enum value: RUN_OUTCOME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The run finished its work.
   *
   * @generated from enum value: RUN_OUTCOME_COMPLETED = 1;
   */
  COMPLETED = 1,

  /**
   * The run stopped on an error.
   *
   * @generated from enum value: RUN_OUTCOME_FAILED = 2;
   */
  FAILED = 2,

  /**
   * The run was told to stop.
   *
   * @generated from enum value: RUN_OUTCOME_CANCELED = 3;
   */
  CANCELED = 3,
}

/**
 * Describes the enum mgmt.v1alpha1.RunOutcome.
 */
export const RunOutcomeSchema: GenEnum<RunOutcome> = /*@__PURE__*/
  enumDesc(file_mgmt_v1alpha1_usage, 0);

/**
 * Holds the counters of what the instance runs.
 *
 * @generated from service mgmt.v1alpha1.UsageService
 */
export const UsageService: GenService<{
  /**
   * Tells that a run has begun. Only the worker calls this, with its key.
   *
   * @generated from rpc mgmt.v1alpha1.UsageService.RecordRunStarted
   */
  recordRunStarted: {
    methodKind: "unary";
    input: typeof RecordRunStartedRequestSchema;
    output: typeof RecordRunStartedResponseSchema;
  },
  /**
   * Tells that a run has ended, and what it did. Only the worker calls this, with its key.
   *
   * @generated from rpc mgmt.v1alpha1.UsageService.RecordRunEnded
   */
  recordRunEnded: {
    methodKind: "unary";
    input: typeof RecordRunEndedRequestSchema;
    output: typeof RecordRunEndedResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_mgmt_v1alpha1_usage, 0);

