// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmw

import (
	"context"
	"net/http"

	"connectrpc.com/connect"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthClient creates a new instance of MockAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthClient is an autogenerated mock type for the AuthClient type
type MockAuthClient struct {
	mock.Mock
}

type MockAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthClient) EXPECT() *MockAuthClient_Expecter {
	return &MockAuthClient_Expecter{mock: &_m.Mock}
}

// InjectTokenCtx provides a mock function for the type MockAuthClient
func (_mock *MockAuthClient) InjectTokenCtx(ctx context.Context, header http.Header, spec connect.Spec) (context.Context, error) {
	ret := _mock.Called(ctx, header, spec)

	if len(ret) == 0 {
		panic("no return value specified for InjectTokenCtx")
	}

	var r0 context.Context
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.Header, connect.Spec) (context.Context, error)); ok {
		return returnFunc(ctx, header, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, http.Header, connect.Spec) context.Context); ok {
		r0 = returnFunc(ctx, header, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, http.Header, connect.Spec) error); ok {
		r1 = returnFunc(ctx, header, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthClient_InjectTokenCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InjectTokenCtx'
type MockAuthClient_InjectTokenCtx_Call struct {
	*mock.Call
}

// InjectTokenCtx is a helper method to define mock.On call
//   - ctx context.Context
//   - header http.Header
//   - spec connect.Spec
func (_e *MockAuthClient_Expecter) InjectTokenCtx(ctx any, header any, spec any) *MockAuthClient_InjectTokenCtx_Call {
	return &MockAuthClient_InjectTokenCtx_Call{Call: _e.mock.On("InjectTokenCtx", ctx, header, spec)}
}

func (_c *MockAuthClient_InjectTokenCtx_Call) Run(run func(ctx context.Context, header http.Header, spec connect.Spec)) *MockAuthClient_InjectTokenCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 http.Header
		if args[1] != nil {
			arg1 = args[1].(http.Header)
		}
		var arg2 connect.Spec
		if args[2] != nil {
			arg2 = args[2].(connect.Spec)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthClient_InjectTokenCtx_Call) Return(context1 context.Context, err error) *MockAuthClient_InjectTokenCtx_Call {
	_c.Call.Return(context1, err)
	return _c
}

func (_c *MockAuthClient_InjectTokenCtx_Call) RunAndReturn(run func(ctx context.Context, header http.Header, spec connect.Spec) (context.Context, error)) *MockAuthClient_InjectTokenCtx_Call {
	_c.Call.Return(run)
	return _c
}
