releases:
  - name: husonym-app
    chart: ../../../charts/app
    version: 'v0.0.0'
    namespace: husonym
    createNamespace: false

    values:
      -
        image:
          repository: husonym-app

        serviceAccount:
          create: true

        husonymEnv: dev

        servicePort: 80
        containerPort: 3000

        husonymApi:
          url: http://husonym-api

        auth:
          enabled: false

