// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package piidetect_table_activities

import (
	"context"

	"github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOpenAiCompletionsClient creates a new instance of MockOpenAiCompletionsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOpenAiCompletionsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOpenAiCompletionsClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockOpenAiCompletionsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockOpenAiCompletionsClient is an autogenerated mock type for the OpenAiCompletionsClient type
type MockOpenAiCompletionsClient struct {
	mock.Mock
}

type MockOpenAiCompletionsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOpenAiCompletionsClient) EXPECT() *MockOpenAiCompletionsClient_Expecter {
	return &MockOpenAiCompletionsClient_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type MockOpenAiCompletionsClient
func (_mock *MockOpenAiCompletionsClient) New(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption) (*openai.ChatCompletion, error) {
	// option.RequestOption
	_va := make([]any, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, body)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 *openai.ChatCompletion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, openai.ChatCompletionNewParams, ...option.RequestOption) (*openai.ChatCompletion, error)); ok {
		return returnFunc(ctx, body, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, openai.ChatCompletionNewParams, ...option.RequestOption) *openai.ChatCompletion); ok {
		r0 = returnFunc(ctx, body, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*openai.ChatCompletion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, openai.ChatCompletionNewParams, ...option.RequestOption) error); ok {
		r1 = returnFunc(ctx, body, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOpenAiCompletionsClient_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type MockOpenAiCompletionsClient_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - ctx context.Context
//   - body openai.ChatCompletionNewParams
//   - opts ...option.RequestOption
func (_e *MockOpenAiCompletionsClient_Expecter) New(ctx any, body any, opts ...any) *MockOpenAiCompletionsClient_New_Call {
	return &MockOpenAiCompletionsClient_New_Call{Call: _e.mock.On("New",
		append([]any{ctx, body}, opts...)...)}
}

func (_c *MockOpenAiCompletionsClient_New_Call) Run(run func(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption)) *MockOpenAiCompletionsClient_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 openai.ChatCompletionNewParams
		if args[1] != nil {
			arg1 = args[1].(openai.ChatCompletionNewParams)
		}
		var arg2 []option.RequestOption
		variadicArgs := make([]option.RequestOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(option.RequestOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockOpenAiCompletionsClient_New_Call) Return(res *openai.ChatCompletion, err error) *MockOpenAiCompletionsClient_New_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *MockOpenAiCompletionsClient_New_Call) RunAndReturn(run func(ctx context.Context, body openai.ChatCompletionNewParams, opts ...option.RequestOption) (*openai.ChatCompletion, error)) *MockOpenAiCompletionsClient_New_Call {
	_c.Call.Return(run)
	return _c
}
