// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mongoconnect

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/mongo"
)

// NewMockDbContainer creates a new instance of MockDbContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDbContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDbContainer {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDbContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDbContainer is an autogenerated mock type for the DbContainer type
type MockDbContainer struct {
	mock.Mock
}

type MockDbContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDbContainer) EXPECT() *MockDbContainer_Expecter {
	return &MockDbContainer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDbContainer
func (_mock *MockDbContainer) Close(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDbContainer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDbContainer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockDbContainer_Expecter) Close(context1 any) *MockDbContainer_Close_Call {
	return &MockDbContainer_Close_Call{Call: _e.mock.On("Close", context1)}
}

func (_c *MockDbContainer_Close_Call) Run(run func(context1 context.Context)) *MockDbContainer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDbContainer_Close_Call) Return(err error) *MockDbContainer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDbContainer_Close_Call) RunAndReturn(run func(context1 context.Context) error) *MockDbContainer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockDbContainer
func (_mock *MockDbContainer) Open(ctx context.Context) (*mongo.Client, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 *mongo.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*mongo.Client, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *mongo.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mongo.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDbContainer_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockDbContainer_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDbContainer_Expecter) Open(ctx any) *MockDbContainer_Open_Call {
	return &MockDbContainer_Open_Call{Call: _e.mock.On("Open", ctx)}
}

func (_c *MockDbContainer_Open_Call) Run(run func(ctx context.Context)) *MockDbContainer_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDbContainer_Open_Call) Return(client *mongo.Client, err error) *MockDbContainer_Open_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *MockDbContainer_Open_Call) RunAndReturn(run func(ctx context.Context) (*mongo.Client, error)) *MockDbContainer_Open_Call {
	_c.Call.Return(run)
	return _c
}
