apiVersion: v1
kind: Secret
metadata:
    name: {{ template "husonym-api.fullname" . }}-service-evs-{{ include "husonym-api.env-vars" . | sha256sum | trunc 8 }}
    namespace: {{ .Release.Namespace }}
    annotations:
        checksum/stringdata: {{ include "husonym-api.env-vars" . | sha256sum }}
type: Opaque
stringData:
{{ include "husonym-api.env-vars" . | indent 4 }}
