// Les helpers de formatage des attributs de colonne (GENERATED / IDENTITY).
// Le composant AttributesCell qui les affichait en badges a été remplacé par la
// colonne « Attributes » texte de SchemaTable.

export function getIdentityStatement(identityType: string): string {
  if (identityType === 'a') {
    return 'GENERATED ALWAYS AS IDENTITY';
  } else if (identityType === 'd') {
    return 'GENERATED BY DEFAULT AS IDENTITY';
  } else if (identityType === 'auto_increment') {
    return 'AUTO_INCREMENT';
  }
  return identityType;
}

export function getGeneratedStatement(generatedType: string): string {
  if (generatedType === 's' || generatedType === 'STORED GENERATED') {
    return 'GENERATED ALWAYS AS STORED';
  } else if (generatedType === 'v' || generatedType === 'VIRTUAL GENERATED') {
    return 'GENERATED ALWAYS AS VIRTUAL';
  }
  return generatedType;
}
